package com.caoc.test.mapper;


import com.caoc.test.domain.TLendApply;
import com.caoc.test.domain.TLendApplyExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface TLendApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int countByExample(TLendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int deleteByExample(TLendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `t_lend_apply`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `t_lend_apply` (`id`, `lend_apply_no`, ",
        "`uid`, `order_no`, `parent_biz_serial`, ",
        "`biz_serial`, `biz_type`, ",
        "`lend_type`, `lend_card_id`, ",
        "`repay_card_id`, `asset_product_id`, ",
        "`asset_bank`, `apply_time`, ",
        "`apply_status`, `lend_amount`, ",
        "`stage`, `source`, `lend_purpose`, ",
        "`interest_type`, `fee_rate`, ",
        "`updated_at`, `create_by`, ",
        "`update_by`, `version_number`, ",
        "`status_desc`, `account_type`, ",
        "`ext_no`, `created_at`, ",
        "`lend_fee_rate`, `customer_irr`, ",
        "`coupon_id`, `coupon_type`, ",
        "`biz_type_tag`, `hold_time`)",
        "values (#{id,jdbcType=INTEGER}, #{lendApplyNo,jdbcType=CHAR}, ",
        "#{uid,jdbcType=CHAR}, #{orderNo,jdbcType=VARCHAR}, #{parentBizSerial,jdbcType=VARCHAR}, ",
        "#{bizSerial,jdbcType=VARCHAR}, #{bizType,jdbcType=VARCHAR}, ",
        "#{lendType,jdbcType=VARCHAR}, #{lendCardId,jdbcType=VARCHAR}, ",
        "#{repayCardId,jdbcType=VARCHAR}, #{assetProductId,jdbcType=VARCHAR}, ",
        "#{assetBank,jdbcType=VARCHAR}, #{applyTime,jdbcType=TIMESTAMP}, ",
        "#{applyStatus,jdbcType=VARCHAR}, #{lendAmount,jdbcType=INTEGER}, ",
        "#{stage,jdbcType=TINYINT}, #{source,jdbcType=VARCHAR}, #{lendPurpose,jdbcType=VARCHAR}, ",
        "#{interestType,jdbcType=VARCHAR}, #{feeRate,jdbcType=DECIMAL}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ",
        "#{updateBy,jdbcType=VARCHAR}, #{versionNumber,jdbcType=INTEGER}, ",
        "#{statusDesc,jdbcType=VARCHAR}, #{accountType,jdbcType=VARCHAR}, ",
        "#{extNo,jdbcType=CHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{lendFeeRate,jdbcType=DECIMAL}, #{customerIrr,jdbcType=DECIMAL}, ",
        "#{couponId,jdbcType=VARCHAR}, #{couponType,jdbcType=VARCHAR}, ",
        "#{bizTypeTag,jdbcType=VARCHAR}, #{holdTime,jdbcType=TIMESTAMP})"
    })
    int insert(TLendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int insertSelective(TLendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    List<TLendApply> selectByExample(TLendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `lend_apply_no`, `uid`, `order_no`, `parent_biz_serial`, `biz_serial`, ",
        "`biz_type`, `lend_type`, `lend_card_id`, `repay_card_id`, `asset_product_id`, ",
        "`asset_bank`, `apply_time`, `apply_status`, `lend_amount`, `stage`, `source`, ",
        "`lend_purpose`, `interest_type`, `fee_rate`, `updated_at`, `create_by`, `update_by`, ",
        "`version_number`, `status_desc`, `account_type`, `ext_no`, `created_at`, `lend_fee_rate`, ",
        "`customer_irr`, `coupon_id`, `coupon_type`, `biz_type_tag`, `hold_time`",
        "from `t_lend_apply`",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TLendApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TLendApply record, @Param("example") TLendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TLendApply record, @Param("example") TLendApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TLendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    @Update({
        "update `t_lend_apply`",
        "set `lend_apply_no` = #{lendApplyNo,jdbcType=CHAR},",
          "`uid` = #{uid,jdbcType=CHAR},",
          "`order_no` = #{orderNo,jdbcType=VARCHAR},",
          "`parent_biz_serial` = #{parentBizSerial,jdbcType=VARCHAR},",
          "`biz_serial` = #{bizSerial,jdbcType=VARCHAR},",
          "`biz_type` = #{bizType,jdbcType=VARCHAR},",
          "`lend_type` = #{lendType,jdbcType=VARCHAR},",
          "`lend_card_id` = #{lendCardId,jdbcType=VARCHAR},",
          "`repay_card_id` = #{repayCardId,jdbcType=VARCHAR},",
          "`asset_product_id` = #{assetProductId,jdbcType=VARCHAR},",
          "`asset_bank` = #{assetBank,jdbcType=VARCHAR},",
          "`apply_time` = #{applyTime,jdbcType=TIMESTAMP},",
          "`apply_status` = #{applyStatus,jdbcType=VARCHAR},",
          "`lend_amount` = #{lendAmount,jdbcType=INTEGER},",
          "`stage` = #{stage,jdbcType=TINYINT},",
          "`source` = #{source,jdbcType=VARCHAR},",
          "`lend_purpose` = #{lendPurpose,jdbcType=VARCHAR},",
          "`interest_type` = #{interestType,jdbcType=VARCHAR},",
          "`fee_rate` = #{feeRate,jdbcType=DECIMAL},",
          "`updated_at` = #{updatedAt,jdbcType=TIMESTAMP},",
          "`create_by` = #{createBy,jdbcType=VARCHAR},",
          "`update_by` = #{updateBy,jdbcType=VARCHAR},",
          "`version_number` = #{versionNumber,jdbcType=INTEGER},",
          "`status_desc` = #{statusDesc,jdbcType=VARCHAR},",
          "`account_type` = #{accountType,jdbcType=VARCHAR},",
          "`ext_no` = #{extNo,jdbcType=CHAR},",
          "`created_at` = #{createdAt,jdbcType=TIMESTAMP},",
          "`lend_fee_rate` = #{lendFeeRate,jdbcType=DECIMAL},",
          "`customer_irr` = #{customerIrr,jdbcType=DECIMAL},",
          "`coupon_id` = #{couponId,jdbcType=VARCHAR},",
          "`coupon_type` = #{couponType,jdbcType=VARCHAR},",
          "`biz_type_tag` = #{bizTypeTag,jdbcType=VARCHAR},",
          "`hold_time` = #{holdTime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLendApply record);

    List<String> findReBuildLendApply(@Param("begin") String begin, @Param("end") String end);
}