package com.ethan.test.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CasFLendengineLightAssetDataFromLoanTempExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public CasFLendengineLightAssetDataFromLoanTempExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDdNoIsNull() {
            addCriterion("`dd_no` is null");
            return (Criteria) this;
        }

        public Criteria andDdNoIsNotNull() {
            addCriterion("`dd_no` is not null");
            return (Criteria) this;
        }

        public Criteria andDdNoEqualTo(String value) {
            addCriterion("`dd_no` =", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoNotEqualTo(String value) {
            addCriterion("`dd_no` <>", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoGreaterThan(String value) {
            addCriterion("`dd_no` >", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoGreaterThanOrEqualTo(String value) {
            addCriterion("`dd_no` >=", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoLessThan(String value) {
            addCriterion("`dd_no` <", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoLessThanOrEqualTo(String value) {
            addCriterion("`dd_no` <=", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoLike(String value) {
            addCriterion("`dd_no` like", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoNotLike(String value) {
            addCriterion("`dd_no` not like", value, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoIn(List<String> values) {
            addCriterion("`dd_no` in", values, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoNotIn(List<String> values) {
            addCriterion("`dd_no` not in", values, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoBetween(String value1, String value2) {
            addCriterion("`dd_no` between", value1, value2, "ddNo");
            return (Criteria) this;
        }

        public Criteria andDdNoNotBetween(String value1, String value2) {
            addCriterion("`dd_no` not between", value1, value2, "ddNo");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andJkkIdIsNull() {
            addCriterion("`jkk_id` is null");
            return (Criteria) this;
        }

        public Criteria andJkkIdIsNotNull() {
            addCriterion("`jkk_id` is not null");
            return (Criteria) this;
        }

        public Criteria andJkkIdEqualTo(String value) {
            addCriterion("`jkk_id` =", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdNotEqualTo(String value) {
            addCriterion("`jkk_id` <>", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdGreaterThan(String value) {
            addCriterion("`jkk_id` >", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdGreaterThanOrEqualTo(String value) {
            addCriterion("`jkk_id` >=", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdLessThan(String value) {
            addCriterion("`jkk_id` <", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdLessThanOrEqualTo(String value) {
            addCriterion("`jkk_id` <=", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdLike(String value) {
            addCriterion("`jkk_id` like", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdNotLike(String value) {
            addCriterion("`jkk_id` not like", value, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdIn(List<String> values) {
            addCriterion("`jkk_id` in", values, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdNotIn(List<String> values) {
            addCriterion("`jkk_id` not in", values, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdBetween(String value1, String value2) {
            addCriterion("`jkk_id` between", value1, value2, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkkIdNotBetween(String value1, String value2) {
            addCriterion("`jkk_id` not between", value1, value2, "jkkId");
            return (Criteria) this;
        }

        public Criteria andJkJjIsNull() {
            addCriterion("`jk_jj` is null");
            return (Criteria) this;
        }

        public Criteria andJkJjIsNotNull() {
            addCriterion("`jk_jj` is not null");
            return (Criteria) this;
        }

        public Criteria andJkJjEqualTo(Integer value) {
            addCriterion("`jk_jj` =", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjNotEqualTo(Integer value) {
            addCriterion("`jk_jj` <>", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjGreaterThan(Integer value) {
            addCriterion("`jk_jj` >", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjGreaterThanOrEqualTo(Integer value) {
            addCriterion("`jk_jj` >=", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjLessThan(Integer value) {
            addCriterion("`jk_jj` <", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjLessThanOrEqualTo(Integer value) {
            addCriterion("`jk_jj` <=", value, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjIn(List<Integer> values) {
            addCriterion("`jk_jj` in", values, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjNotIn(List<Integer> values) {
            addCriterion("`jk_jj` not in", values, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjBetween(Integer value1, Integer value2) {
            addCriterion("`jk_jj` between", value1, value2, "jkJj");
            return (Criteria) this;
        }

        public Criteria andJkJjNotBetween(Integer value1, Integer value2) {
            addCriterion("`jk_jj` not between", value1, value2, "jkJj");
            return (Criteria) this;
        }

        public Criteria andFqsIsNull() {
            addCriterion("`fqs` is null");
            return (Criteria) this;
        }

        public Criteria andFqsIsNotNull() {
            addCriterion("`fqs` is not null");
            return (Criteria) this;
        }

        public Criteria andFqsEqualTo(Byte value) {
            addCriterion("`fqs` =", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsNotEqualTo(Byte value) {
            addCriterion("`fqs` <>", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsGreaterThan(Byte value) {
            addCriterion("`fqs` >", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsGreaterThanOrEqualTo(Byte value) {
            addCriterion("`fqs` >=", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsLessThan(Byte value) {
            addCriterion("`fqs` <", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsLessThanOrEqualTo(Byte value) {
            addCriterion("`fqs` <=", value, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsIn(List<Byte> values) {
            addCriterion("`fqs` in", values, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsNotIn(List<Byte> values) {
            addCriterion("`fqs` not in", values, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsBetween(Byte value1, Byte value2) {
            addCriterion("`fqs` between", value1, value2, "fqs");
            return (Criteria) this;
        }

        public Criteria andFqsNotBetween(Byte value1, Byte value2) {
            addCriterion("`fqs` not between", value1, value2, "fqs");
            return (Criteria) this;
        }

        public Criteria andSqZtIsNull() {
            addCriterion("`sq_zt` is null");
            return (Criteria) this;
        }

        public Criteria andSqZtIsNotNull() {
            addCriterion("`sq_zt` is not null");
            return (Criteria) this;
        }

        public Criteria andSqZtEqualTo(String value) {
            addCriterion("`sq_zt` =", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtNotEqualTo(String value) {
            addCriterion("`sq_zt` <>", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtGreaterThan(String value) {
            addCriterion("`sq_zt` >", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtGreaterThanOrEqualTo(String value) {
            addCriterion("`sq_zt` >=", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtLessThan(String value) {
            addCriterion("`sq_zt` <", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtLessThanOrEqualTo(String value) {
            addCriterion("`sq_zt` <=", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtLike(String value) {
            addCriterion("`sq_zt` like", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtNotLike(String value) {
            addCriterion("`sq_zt` not like", value, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtIn(List<String> values) {
            addCriterion("`sq_zt` in", values, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtNotIn(List<String> values) {
            addCriterion("`sq_zt` not in", values, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtBetween(String value1, String value2) {
            addCriterion("`sq_zt` between", value1, value2, "sqZt");
            return (Criteria) this;
        }

        public Criteria andSqZtNotBetween(String value1, String value2) {
            addCriterion("`sq_zt` not between", value1, value2, "sqZt");
            return (Criteria) this;
        }

        public Criteria andCjSjIsNull() {
            addCriterion("`cj_sj` is null");
            return (Criteria) this;
        }

        public Criteria andCjSjIsNotNull() {
            addCriterion("`cj_sj` is not null");
            return (Criteria) this;
        }

        public Criteria andCjSjEqualTo(Date value) {
            addCriterion("`cj_sj` =", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjNotEqualTo(Date value) {
            addCriterion("`cj_sj` <>", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjGreaterThan(Date value) {
            addCriterion("`cj_sj` >", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjGreaterThanOrEqualTo(Date value) {
            addCriterion("`cj_sj` >=", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjLessThan(Date value) {
            addCriterion("`cj_sj` <", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjLessThanOrEqualTo(Date value) {
            addCriterion("`cj_sj` <=", value, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjIn(List<Date> values) {
            addCriterion("`cj_sj` in", values, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjNotIn(List<Date> values) {
            addCriterion("`cj_sj` not in", values, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjBetween(Date value1, Date value2) {
            addCriterion("`cj_sj` between", value1, value2, "cjSj");
            return (Criteria) this;
        }

        public Criteria andCjSjNotBetween(Date value1, Date value2) {
            addCriterion("`cj_sj` not between", value1, value2, "cjSj");
            return (Criteria) this;
        }

        public Criteria andGxSjIsNull() {
            addCriterion("`gx_sj` is null");
            return (Criteria) this;
        }

        public Criteria andGxSjIsNotNull() {
            addCriterion("`gx_sj` is not null");
            return (Criteria) this;
        }

        public Criteria andGxSjEqualTo(Date value) {
            addCriterion("`gx_sj` =", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjNotEqualTo(Date value) {
            addCriterion("`gx_sj` <>", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjGreaterThan(Date value) {
            addCriterion("`gx_sj` >", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjGreaterThanOrEqualTo(Date value) {
            addCriterion("`gx_sj` >=", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjLessThan(Date value) {
            addCriterion("`gx_sj` <", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjLessThanOrEqualTo(Date value) {
            addCriterion("`gx_sj` <=", value, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjIn(List<Date> values) {
            addCriterion("`gx_sj` in", values, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjNotIn(List<Date> values) {
            addCriterion("`gx_sj` not in", values, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjBetween(Date value1, Date value2) {
            addCriterion("`gx_sj` between", value1, value2, "gxSj");
            return (Criteria) this;
        }

        public Criteria andGxSjNotBetween(Date value1, Date value2) {
            addCriterion("`gx_sj` not between", value1, value2, "gxSj");
            return (Criteria) this;
        }

        public Criteria andSqNoIsNull() {
            addCriterion("`sq_no` is null");
            return (Criteria) this;
        }

        public Criteria andSqNoIsNotNull() {
            addCriterion("`sq_no` is not null");
            return (Criteria) this;
        }

        public Criteria andSqNoEqualTo(String value) {
            addCriterion("`sq_no` =", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoNotEqualTo(String value) {
            addCriterion("`sq_no` <>", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoGreaterThan(String value) {
            addCriterion("`sq_no` >", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoGreaterThanOrEqualTo(String value) {
            addCriterion("`sq_no` >=", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoLessThan(String value) {
            addCriterion("`sq_no` <", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoLessThanOrEqualTo(String value) {
            addCriterion("`sq_no` <=", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoLike(String value) {
            addCriterion("`sq_no` like", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoNotLike(String value) {
            addCriterion("`sq_no` not like", value, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoIn(List<String> values) {
            addCriterion("`sq_no` in", values, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoNotIn(List<String> values) {
            addCriterion("`sq_no` not in", values, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoBetween(String value1, String value2) {
            addCriterion("`sq_no` between", value1, value2, "sqNo");
            return (Criteria) this;
        }

        public Criteria andSqNoNotBetween(String value1, String value2) {
            addCriterion("`sq_no` not between", value1, value2, "sqNo");
            return (Criteria) this;
        }

        public Criteria andFkZfIsNull() {
            addCriterion("`fk_zf` is null");
            return (Criteria) this;
        }

        public Criteria andFkZfIsNotNull() {
            addCriterion("`fk_zf` is not null");
            return (Criteria) this;
        }

        public Criteria andFkZfEqualTo(String value) {
            addCriterion("`fk_zf` =", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfNotEqualTo(String value) {
            addCriterion("`fk_zf` <>", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfGreaterThan(String value) {
            addCriterion("`fk_zf` >", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfGreaterThanOrEqualTo(String value) {
            addCriterion("`fk_zf` >=", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfLessThan(String value) {
            addCriterion("`fk_zf` <", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfLessThanOrEqualTo(String value) {
            addCriterion("`fk_zf` <=", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfLike(String value) {
            addCriterion("`fk_zf` like", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfNotLike(String value) {
            addCriterion("`fk_zf` not like", value, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfIn(List<String> values) {
            addCriterion("`fk_zf` in", values, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfNotIn(List<String> values) {
            addCriterion("`fk_zf` not in", values, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfBetween(String value1, String value2) {
            addCriterion("`fk_zf` between", value1, value2, "fkZf");
            return (Criteria) this;
        }

        public Criteria andFkZfNotBetween(String value1, String value2) {
            addCriterion("`fk_zf` not between", value1, value2, "fkZf");
            return (Criteria) this;
        }

        public Criteria andZsZhIsNull() {
            addCriterion("`zs_zh` is null");
            return (Criteria) this;
        }

        public Criteria andZsZhIsNotNull() {
            addCriterion("`zs_zh` is not null");
            return (Criteria) this;
        }

        public Criteria andZsZhEqualTo(String value) {
            addCriterion("`zs_zh` =", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhNotEqualTo(String value) {
            addCriterion("`zs_zh` <>", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhGreaterThan(String value) {
            addCriterion("`zs_zh` >", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhGreaterThanOrEqualTo(String value) {
            addCriterion("`zs_zh` >=", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhLessThan(String value) {
            addCriterion("`zs_zh` <", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhLessThanOrEqualTo(String value) {
            addCriterion("`zs_zh` <=", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhLike(String value) {
            addCriterion("`zs_zh` like", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhNotLike(String value) {
            addCriterion("`zs_zh` not like", value, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhIn(List<String> values) {
            addCriterion("`zs_zh` in", values, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhNotIn(List<String> values) {
            addCriterion("`zs_zh` not in", values, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhBetween(String value1, String value2) {
            addCriterion("`zs_zh` between", value1, value2, "zsZh");
            return (Criteria) this;
        }

        public Criteria andZsZhNotBetween(String value1, String value2) {
            addCriterion("`zs_zh` not between", value1, value2, "zsZh");
            return (Criteria) this;
        }

        public Criteria andYwIdIsNull() {
            addCriterion("`yw_id` is null");
            return (Criteria) this;
        }

        public Criteria andYwIdIsNotNull() {
            addCriterion("`yw_id` is not null");
            return (Criteria) this;
        }

        public Criteria andYwIdEqualTo(String value) {
            addCriterion("`yw_id` =", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdNotEqualTo(String value) {
            addCriterion("`yw_id` <>", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdGreaterThan(String value) {
            addCriterion("`yw_id` >", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdGreaterThanOrEqualTo(String value) {
            addCriterion("`yw_id` >=", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdLessThan(String value) {
            addCriterion("`yw_id` <", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdLessThanOrEqualTo(String value) {
            addCriterion("`yw_id` <=", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdLike(String value) {
            addCriterion("`yw_id` like", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdNotLike(String value) {
            addCriterion("`yw_id` not like", value, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdIn(List<String> values) {
            addCriterion("`yw_id` in", values, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdNotIn(List<String> values) {
            addCriterion("`yw_id` not in", values, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdBetween(String value1, String value2) {
            addCriterion("`yw_id` between", value1, value2, "ywId");
            return (Criteria) this;
        }

        public Criteria andYwIdNotBetween(String value1, String value2) {
            addCriterion("`yw_id` not between", value1, value2, "ywId");
            return (Criteria) this;
        }

        public Criteria andSqLyIsNull() {
            addCriterion("`sq_ly` is null");
            return (Criteria) this;
        }

        public Criteria andSqLyIsNotNull() {
            addCriterion("`sq_ly` is not null");
            return (Criteria) this;
        }

        public Criteria andSqLyEqualTo(String value) {
            addCriterion("`sq_ly` =", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyNotEqualTo(String value) {
            addCriterion("`sq_ly` <>", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyGreaterThan(String value) {
            addCriterion("`sq_ly` >", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyGreaterThanOrEqualTo(String value) {
            addCriterion("`sq_ly` >=", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyLessThan(String value) {
            addCriterion("`sq_ly` <", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyLessThanOrEqualTo(String value) {
            addCriterion("`sq_ly` <=", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyLike(String value) {
            addCriterion("`sq_ly` like", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyNotLike(String value) {
            addCriterion("`sq_ly` not like", value, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyIn(List<String> values) {
            addCriterion("`sq_ly` in", values, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyNotIn(List<String> values) {
            addCriterion("`sq_ly` not in", values, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyBetween(String value1, String value2) {
            addCriterion("`sq_ly` between", value1, value2, "sqLy");
            return (Criteria) this;
        }

        public Criteria andSqLyNotBetween(String value1, String value2) {
            addCriterion("`sq_ly` not between", value1, value2, "sqLy");
            return (Criteria) this;
        }

        public Criteria andFkZfIdIsNull() {
            addCriterion("`fk_zf_id` is null");
            return (Criteria) this;
        }

        public Criteria andFkZfIdIsNotNull() {
            addCriterion("`fk_zf_id` is not null");
            return (Criteria) this;
        }

        public Criteria andFkZfIdEqualTo(String value) {
            addCriterion("`fk_zf_id` =", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdNotEqualTo(String value) {
            addCriterion("`fk_zf_id` <>", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdGreaterThan(String value) {
            addCriterion("`fk_zf_id` >", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdGreaterThanOrEqualTo(String value) {
            addCriterion("`fk_zf_id` >=", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdLessThan(String value) {
            addCriterion("`fk_zf_id` <", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdLessThanOrEqualTo(String value) {
            addCriterion("`fk_zf_id` <=", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdLike(String value) {
            addCriterion("`fk_zf_id` like", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdNotLike(String value) {
            addCriterion("`fk_zf_id` not like", value, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdIn(List<String> values) {
            addCriterion("`fk_zf_id` in", values, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdNotIn(List<String> values) {
            addCriterion("`fk_zf_id` not in", values, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdBetween(String value1, String value2) {
            addCriterion("`fk_zf_id` between", value1, value2, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andFkZfIdNotBetween(String value1, String value2) {
            addCriterion("`fk_zf_id` not between", value1, value2, "fkZfId");
            return (Criteria) this;
        }

        public Criteria andYhqIdIsNull() {
            addCriterion("`yhq_id` is null");
            return (Criteria) this;
        }

        public Criteria andYhqIdIsNotNull() {
            addCriterion("`yhq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andYhqIdEqualTo(String value) {
            addCriterion("`yhq_id` =", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdNotEqualTo(String value) {
            addCriterion("`yhq_id` <>", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdGreaterThan(String value) {
            addCriterion("`yhq_id` >", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`yhq_id` >=", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdLessThan(String value) {
            addCriterion("`yhq_id` <", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdLessThanOrEqualTo(String value) {
            addCriterion("`yhq_id` <=", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdLike(String value) {
            addCriterion("`yhq_id` like", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdNotLike(String value) {
            addCriterion("`yhq_id` not like", value, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdIn(List<String> values) {
            addCriterion("`yhq_id` in", values, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdNotIn(List<String> values) {
            addCriterion("`yhq_id` not in", values, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdBetween(String value1, String value2) {
            addCriterion("`yhq_id` between", value1, value2, "yhqId");
            return (Criteria) this;
        }

        public Criteria andYhqIdNotBetween(String value1, String value2) {
            addCriterion("`yhq_id` not between", value1, value2, "yhqId");
            return (Criteria) this;
        }

        public Criteria andEtlIdIsNull() {
            addCriterion("`etl_id` is null");
            return (Criteria) this;
        }

        public Criteria andEtlIdIsNotNull() {
            addCriterion("`etl_id` is not null");
            return (Criteria) this;
        }

        public Criteria andEtlIdEqualTo(Integer value) {
            addCriterion("`etl_id` =", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdNotEqualTo(Integer value) {
            addCriterion("`etl_id` <>", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdGreaterThan(Integer value) {
            addCriterion("`etl_id` >", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`etl_id` >=", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdLessThan(Integer value) {
            addCriterion("`etl_id` <", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdLessThanOrEqualTo(Integer value) {
            addCriterion("`etl_id` <=", value, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdIn(List<Integer> values) {
            addCriterion("`etl_id` in", values, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdNotIn(List<Integer> values) {
            addCriterion("`etl_id` not in", values, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdBetween(Integer value1, Integer value2) {
            addCriterion("`etl_id` between", value1, value2, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`etl_id` not between", value1, value2, "etlId");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimIsNull() {
            addCriterion("`etl_crt_tim` is null");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimIsNotNull() {
            addCriterion("`etl_crt_tim` is not null");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimEqualTo(Date value) {
            addCriterion("`etl_crt_tim` =", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimNotEqualTo(Date value) {
            addCriterion("`etl_crt_tim` <>", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimGreaterThan(Date value) {
            addCriterion("`etl_crt_tim` >", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimGreaterThanOrEqualTo(Date value) {
            addCriterion("`etl_crt_tim` >=", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimLessThan(Date value) {
            addCriterion("`etl_crt_tim` <", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimLessThanOrEqualTo(Date value) {
            addCriterion("`etl_crt_tim` <=", value, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimIn(List<Date> values) {
            addCriterion("`etl_crt_tim` in", values, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimNotIn(List<Date> values) {
            addCriterion("`etl_crt_tim` not in", values, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimBetween(Date value1, Date value2) {
            addCriterion("`etl_crt_tim` between", value1, value2, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlCrtTimNotBetween(Date value1, Date value2) {
            addCriterion("`etl_crt_tim` not between", value1, value2, "etlCrtTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimIsNull() {
            addCriterion("`etl_upd_tim` is null");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimIsNotNull() {
            addCriterion("`etl_upd_tim` is not null");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimEqualTo(Date value) {
            addCriterion("`etl_upd_tim` =", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimNotEqualTo(Date value) {
            addCriterion("`etl_upd_tim` <>", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimGreaterThan(Date value) {
            addCriterion("`etl_upd_tim` >", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimGreaterThanOrEqualTo(Date value) {
            addCriterion("`etl_upd_tim` >=", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimLessThan(Date value) {
            addCriterion("`etl_upd_tim` <", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimLessThanOrEqualTo(Date value) {
            addCriterion("`etl_upd_tim` <=", value, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimIn(List<Date> values) {
            addCriterion("`etl_upd_tim` in", values, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimNotIn(List<Date> values) {
            addCriterion("`etl_upd_tim` not in", values, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimBetween(Date value1, Date value2) {
            addCriterion("`etl_upd_tim` between", value1, value2, "etlUpdTim");
            return (Criteria) this;
        }

        public Criteria andEtlUpdTimNotBetween(Date value1, Date value2) {
            addCriterion("`etl_upd_tim` not between", value1, value2, "etlUpdTim");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}