package com.ethan.test.domain;

import java.util.Date;

public class CasFLendengineLightAssetDataFromLoanTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.dd_no
     *
     * @mbggenerated
     */
    private String ddNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.jkk_id
     *
     * @mbggenerated
     */
    private String jkkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.jk_jj
     *
     * @mbggenerated
     */
    private Integer jkJj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.fqs
     *
     * @mbggenerated
     */
    private Byte fqs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_zt
     *
     * @mbggenerated
     */
    private String sqZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.cj_sj
     *
     * @mbggenerated
     */
    private Date cjSj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.gx_sj
     *
     * @mbggenerated
     */
    private Date gxSj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_no
     *
     * @mbggenerated
     */
    private String sqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf
     *
     * @mbggenerated
     */
    private String fkZf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.zs_zh
     *
     * @mbggenerated
     */
    private String zsZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.yw_id
     *
     * @mbggenerated
     */
    private String ywId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_ly
     *
     * @mbggenerated
     */
    private String sqLy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf_id
     *
     * @mbggenerated
     */
    private String fkZfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.yhq_id
     *
     * @mbggenerated
     */
    private String yhqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_id
     *
     * @mbggenerated
     */
    private Integer etlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_crt_tim
     *
     * @mbggenerated
     */
    private Date etlCrtTim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_upd_tim
     *
     * @mbggenerated
     */
    private Date etlUpdTim;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public CasFLendengineLightAssetDataFromLoanTemp(String ddNo, String uid, String jkkId, Integer jkJj, Byte fqs, String sqZt, Date cjSj, Date gxSj, String sqNo, String fkZf, String zsZh, String ywId, String sqLy, String fkZfId, String yhqId, Integer etlId, Date etlCrtTim, Date etlUpdTim) {
        this.ddNo = ddNo;
        this.uid = uid;
        this.jkkId = jkkId;
        this.jkJj = jkJj;
        this.fqs = fqs;
        this.sqZt = sqZt;
        this.cjSj = cjSj;
        this.gxSj = gxSj;
        this.sqNo = sqNo;
        this.fkZf = fkZf;
        this.zsZh = zsZh;
        this.ywId = ywId;
        this.sqLy = sqLy;
        this.fkZfId = fkZfId;
        this.yhqId = yhqId;
        this.etlId = etlId;
        this.etlCrtTim = etlCrtTim;
        this.etlUpdTim = etlUpdTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_f_lendengine_light_asset_data_from_loan_temp
     *
     * @mbggenerated
     */
    public CasFLendengineLightAssetDataFromLoanTemp() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.dd_no
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.dd_no
     *
     * @mbggenerated
     */
    public String getDdNo() {
        return ddNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.dd_no
     *
     * @param ddNo the value for cas_f_lendengine_light_asset_data_from_loan_temp.dd_no
     *
     * @mbggenerated
     */
    public void setDdNo(String ddNo) {
        this.ddNo = ddNo == null ? null : ddNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.uid
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.uid
     *
     * @param uid the value for cas_f_lendengine_light_asset_data_from_loan_temp.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.jkk_id
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.jkk_id
     *
     * @mbggenerated
     */
    public String getJkkId() {
        return jkkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.jkk_id
     *
     * @param jkkId the value for cas_f_lendengine_light_asset_data_from_loan_temp.jkk_id
     *
     * @mbggenerated
     */
    public void setJkkId(String jkkId) {
        this.jkkId = jkkId == null ? null : jkkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.jk_jj
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.jk_jj
     *
     * @mbggenerated
     */
    public Integer getJkJj() {
        return jkJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.jk_jj
     *
     * @param jkJj the value for cas_f_lendengine_light_asset_data_from_loan_temp.jk_jj
     *
     * @mbggenerated
     */
    public void setJkJj(Integer jkJj) {
        this.jkJj = jkJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fqs
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.fqs
     *
     * @mbggenerated
     */
    public Byte getFqs() {
        return fqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fqs
     *
     * @param fqs the value for cas_f_lendengine_light_asset_data_from_loan_temp.fqs
     *
     * @mbggenerated
     */
    public void setFqs(Byte fqs) {
        this.fqs = fqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_zt
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.sq_zt
     *
     * @mbggenerated
     */
    public String getSqZt() {
        return sqZt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_zt
     *
     * @param sqZt the value for cas_f_lendengine_light_asset_data_from_loan_temp.sq_zt
     *
     * @mbggenerated
     */
    public void setSqZt(String sqZt) {
        this.sqZt = sqZt == null ? null : sqZt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.cj_sj
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.cj_sj
     *
     * @mbggenerated
     */
    public Date getCjSj() {
        return cjSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.cj_sj
     *
     * @param cjSj the value for cas_f_lendengine_light_asset_data_from_loan_temp.cj_sj
     *
     * @mbggenerated
     */
    public void setCjSj(Date cjSj) {
        this.cjSj = cjSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.gx_sj
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.gx_sj
     *
     * @mbggenerated
     */
    public Date getGxSj() {
        return gxSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.gx_sj
     *
     * @param gxSj the value for cas_f_lendengine_light_asset_data_from_loan_temp.gx_sj
     *
     * @mbggenerated
     */
    public void setGxSj(Date gxSj) {
        this.gxSj = gxSj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_no
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.sq_no
     *
     * @mbggenerated
     */
    public String getSqNo() {
        return sqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_no
     *
     * @param sqNo the value for cas_f_lendengine_light_asset_data_from_loan_temp.sq_no
     *
     * @mbggenerated
     */
    public void setSqNo(String sqNo) {
        this.sqNo = sqNo == null ? null : sqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf
     *
     * @mbggenerated
     */
    public String getFkZf() {
        return fkZf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf
     *
     * @param fkZf the value for cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf
     *
     * @mbggenerated
     */
    public void setFkZf(String fkZf) {
        this.fkZf = fkZf == null ? null : fkZf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.zs_zh
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.zs_zh
     *
     * @mbggenerated
     */
    public String getZsZh() {
        return zsZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.zs_zh
     *
     * @param zsZh the value for cas_f_lendengine_light_asset_data_from_loan_temp.zs_zh
     *
     * @mbggenerated
     */
    public void setZsZh(String zsZh) {
        this.zsZh = zsZh == null ? null : zsZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.yw_id
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.yw_id
     *
     * @mbggenerated
     */
    public String getYwId() {
        return ywId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.yw_id
     *
     * @param ywId the value for cas_f_lendengine_light_asset_data_from_loan_temp.yw_id
     *
     * @mbggenerated
     */
    public void setYwId(String ywId) {
        this.ywId = ywId == null ? null : ywId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_ly
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.sq_ly
     *
     * @mbggenerated
     */
    public String getSqLy() {
        return sqLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.sq_ly
     *
     * @param sqLy the value for cas_f_lendengine_light_asset_data_from_loan_temp.sq_ly
     *
     * @mbggenerated
     */
    public void setSqLy(String sqLy) {
        this.sqLy = sqLy == null ? null : sqLy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf_id
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf_id
     *
     * @mbggenerated
     */
    public String getFkZfId() {
        return fkZfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf_id
     *
     * @param fkZfId the value for cas_f_lendengine_light_asset_data_from_loan_temp.fk_zf_id
     *
     * @mbggenerated
     */
    public void setFkZfId(String fkZfId) {
        this.fkZfId = fkZfId == null ? null : fkZfId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.yhq_id
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.yhq_id
     *
     * @mbggenerated
     */
    public String getYhqId() {
        return yhqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.yhq_id
     *
     * @param yhqId the value for cas_f_lendengine_light_asset_data_from_loan_temp.yhq_id
     *
     * @mbggenerated
     */
    public void setYhqId(String yhqId) {
        this.yhqId = yhqId == null ? null : yhqId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_id
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.etl_id
     *
     * @mbggenerated
     */
    public Integer getEtlId() {
        return etlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_id
     *
     * @param etlId the value for cas_f_lendengine_light_asset_data_from_loan_temp.etl_id
     *
     * @mbggenerated
     */
    public void setEtlId(Integer etlId) {
        this.etlId = etlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_crt_tim
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.etl_crt_tim
     *
     * @mbggenerated
     */
    public Date getEtlCrtTim() {
        return etlCrtTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_crt_tim
     *
     * @param etlCrtTim the value for cas_f_lendengine_light_asset_data_from_loan_temp.etl_crt_tim
     *
     * @mbggenerated
     */
    public void setEtlCrtTim(Date etlCrtTim) {
        this.etlCrtTim = etlCrtTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_upd_tim
     *
     * @return the value of cas_f_lendengine_light_asset_data_from_loan_temp.etl_upd_tim
     *
     * @mbggenerated
     */
    public Date getEtlUpdTim() {
        return etlUpdTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_f_lendengine_light_asset_data_from_loan_temp.etl_upd_tim
     *
     * @param etlUpdTim the value for cas_f_lendengine_light_asset_data_from_loan_temp.etl_upd_tim
     *
     * @mbggenerated
     */
    public void setEtlUpdTim(Date etlUpdTim) {
        this.etlUpdTim = etlUpdTim;
    }
}