package com.caoc.test.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TLendApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_apply_no
     *
     * @mbggenerated
     */
    private String lendApplyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.parent_biz_serial
     *
     * @mbggenerated
     */
    private String parentBizSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.biz_serial
     *
     * @mbggenerated
     */
    private String bizSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_type
     *
     * @mbggenerated
     */
    private String lendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_card_id
     *
     * @mbggenerated
     */
    private String lendCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.repay_card_id
     *
     * @mbggenerated
     */
    private String repayCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.asset_product_id
     *
     * @mbggenerated
     */
    private String assetProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.asset_bank
     *
     * @mbggenerated
     */
    private String assetBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_amount
     *
     * @mbggenerated
     */
    private Integer lendAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.stage
     *
     * @mbggenerated
     */
    private Byte stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_purpose
     *
     * @mbggenerated
     */
    private String lendPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.interest_type
     *
     * @mbggenerated
     */
    private String interestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.fee_rate
     *
     * @mbggenerated
     */
    private BigDecimal feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.version_number
     *
     * @mbggenerated
     */
    private Integer versionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.status_desc
     *
     * @mbggenerated
     */
    private String statusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.account_type
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.ext_no
     *
     * @mbggenerated
     */
    private String extNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.lend_fee_rate
     *
     * @mbggenerated
     */
    private BigDecimal lendFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.customer_irr
     *
     * @mbggenerated
     */
    private BigDecimal customerIrr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.coupon_id
     *
     * @mbggenerated
     */
    private String couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.coupon_type
     *
     * @mbggenerated
     */
    private String couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.biz_type_tag
     *
     * @mbggenerated
     */
    private String bizTypeTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend_apply.hold_time
     *
     * @mbggenerated
     */
    private Date holdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public TLendApply(Integer id, String lendApplyNo, String uid, String orderNo, String parentBizSerial, String bizSerial, String bizType, String lendType, String lendCardId, String repayCardId, String assetProductId, String assetBank, Date applyTime, String applyStatus, Integer lendAmount, Byte stage, String source, String lendPurpose, String interestType, BigDecimal feeRate, Date updatedAt, String createBy, String updateBy, Integer versionNumber, String statusDesc, String accountType, String extNo, Date createdAt, BigDecimal lendFeeRate, BigDecimal customerIrr, String couponId, String couponType, String bizTypeTag, Date holdTime) {
        this.id = id;
        this.lendApplyNo = lendApplyNo;
        this.uid = uid;
        this.orderNo = orderNo;
        this.parentBizSerial = parentBizSerial;
        this.bizSerial = bizSerial;
        this.bizType = bizType;
        this.lendType = lendType;
        this.lendCardId = lendCardId;
        this.repayCardId = repayCardId;
        this.assetProductId = assetProductId;
        this.assetBank = assetBank;
        this.applyTime = applyTime;
        this.applyStatus = applyStatus;
        this.lendAmount = lendAmount;
        this.stage = stage;
        this.source = source;
        this.lendPurpose = lendPurpose;
        this.interestType = interestType;
        this.feeRate = feeRate;
        this.updatedAt = updatedAt;
        this.createBy = createBy;
        this.updateBy = updateBy;
        this.versionNumber = versionNumber;
        this.statusDesc = statusDesc;
        this.accountType = accountType;
        this.extNo = extNo;
        this.createdAt = createdAt;
        this.lendFeeRate = lendFeeRate;
        this.customerIrr = customerIrr;
        this.couponId = couponId;
        this.couponType = couponType;
        this.bizTypeTag = bizTypeTag;
        this.holdTime = holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public TLendApply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.id
     *
     * @return the value of t_lend_apply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.id
     *
     * @param id the value for t_lend_apply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_apply_no
     *
     * @return the value of t_lend_apply.lend_apply_no
     *
     * @mbggenerated
     */
    public String getLendApplyNo() {
        return lendApplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_apply_no
     *
     * @param lendApplyNo the value for t_lend_apply.lend_apply_no
     *
     * @mbggenerated
     */
    public void setLendApplyNo(String lendApplyNo) {
        this.lendApplyNo = lendApplyNo == null ? null : lendApplyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.uid
     *
     * @return the value of t_lend_apply.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.uid
     *
     * @param uid the value for t_lend_apply.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.order_no
     *
     * @return the value of t_lend_apply.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.order_no
     *
     * @param orderNo the value for t_lend_apply.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.parent_biz_serial
     *
     * @return the value of t_lend_apply.parent_biz_serial
     *
     * @mbggenerated
     */
    public String getParentBizSerial() {
        return parentBizSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.parent_biz_serial
     *
     * @param parentBizSerial the value for t_lend_apply.parent_biz_serial
     *
     * @mbggenerated
     */
    public void setParentBizSerial(String parentBizSerial) {
        this.parentBizSerial = parentBizSerial == null ? null : parentBizSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.biz_serial
     *
     * @return the value of t_lend_apply.biz_serial
     *
     * @mbggenerated
     */
    public String getBizSerial() {
        return bizSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.biz_serial
     *
     * @param bizSerial the value for t_lend_apply.biz_serial
     *
     * @mbggenerated
     */
    public void setBizSerial(String bizSerial) {
        this.bizSerial = bizSerial == null ? null : bizSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.biz_type
     *
     * @return the value of t_lend_apply.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.biz_type
     *
     * @param bizType the value for t_lend_apply.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_type
     *
     * @return the value of t_lend_apply.lend_type
     *
     * @mbggenerated
     */
    public String getLendType() {
        return lendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_type
     *
     * @param lendType the value for t_lend_apply.lend_type
     *
     * @mbggenerated
     */
    public void setLendType(String lendType) {
        this.lendType = lendType == null ? null : lendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_card_id
     *
     * @return the value of t_lend_apply.lend_card_id
     *
     * @mbggenerated
     */
    public String getLendCardId() {
        return lendCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_card_id
     *
     * @param lendCardId the value for t_lend_apply.lend_card_id
     *
     * @mbggenerated
     */
    public void setLendCardId(String lendCardId) {
        this.lendCardId = lendCardId == null ? null : lendCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.repay_card_id
     *
     * @return the value of t_lend_apply.repay_card_id
     *
     * @mbggenerated
     */
    public String getRepayCardId() {
        return repayCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.repay_card_id
     *
     * @param repayCardId the value for t_lend_apply.repay_card_id
     *
     * @mbggenerated
     */
    public void setRepayCardId(String repayCardId) {
        this.repayCardId = repayCardId == null ? null : repayCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.asset_product_id
     *
     * @return the value of t_lend_apply.asset_product_id
     *
     * @mbggenerated
     */
    public String getAssetProductId() {
        return assetProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.asset_product_id
     *
     * @param assetProductId the value for t_lend_apply.asset_product_id
     *
     * @mbggenerated
     */
    public void setAssetProductId(String assetProductId) {
        this.assetProductId = assetProductId == null ? null : assetProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.asset_bank
     *
     * @return the value of t_lend_apply.asset_bank
     *
     * @mbggenerated
     */
    public String getAssetBank() {
        return assetBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.asset_bank
     *
     * @param assetBank the value for t_lend_apply.asset_bank
     *
     * @mbggenerated
     */
    public void setAssetBank(String assetBank) {
        this.assetBank = assetBank == null ? null : assetBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.apply_time
     *
     * @return the value of t_lend_apply.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.apply_time
     *
     * @param applyTime the value for t_lend_apply.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.apply_status
     *
     * @return the value of t_lend_apply.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.apply_status
     *
     * @param applyStatus the value for t_lend_apply.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_amount
     *
     * @return the value of t_lend_apply.lend_amount
     *
     * @mbggenerated
     */
    public Integer getLendAmount() {
        return lendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_amount
     *
     * @param lendAmount the value for t_lend_apply.lend_amount
     *
     * @mbggenerated
     */
    public void setLendAmount(Integer lendAmount) {
        this.lendAmount = lendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.stage
     *
     * @return the value of t_lend_apply.stage
     *
     * @mbggenerated
     */
    public Byte getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.stage
     *
     * @param stage the value for t_lend_apply.stage
     *
     * @mbggenerated
     */
    public void setStage(Byte stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.source
     *
     * @return the value of t_lend_apply.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.source
     *
     * @param source the value for t_lend_apply.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_purpose
     *
     * @return the value of t_lend_apply.lend_purpose
     *
     * @mbggenerated
     */
    public String getLendPurpose() {
        return lendPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_purpose
     *
     * @param lendPurpose the value for t_lend_apply.lend_purpose
     *
     * @mbggenerated
     */
    public void setLendPurpose(String lendPurpose) {
        this.lendPurpose = lendPurpose == null ? null : lendPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.interest_type
     *
     * @return the value of t_lend_apply.interest_type
     *
     * @mbggenerated
     */
    public String getInterestType() {
        return interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.interest_type
     *
     * @param interestType the value for t_lend_apply.interest_type
     *
     * @mbggenerated
     */
    public void setInterestType(String interestType) {
        this.interestType = interestType == null ? null : interestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.fee_rate
     *
     * @return the value of t_lend_apply.fee_rate
     *
     * @mbggenerated
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.fee_rate
     *
     * @param feeRate the value for t_lend_apply.fee_rate
     *
     * @mbggenerated
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.updated_at
     *
     * @return the value of t_lend_apply.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.updated_at
     *
     * @param updatedAt the value for t_lend_apply.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.create_by
     *
     * @return the value of t_lend_apply.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.create_by
     *
     * @param createBy the value for t_lend_apply.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.update_by
     *
     * @return the value of t_lend_apply.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.update_by
     *
     * @param updateBy the value for t_lend_apply.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.version_number
     *
     * @return the value of t_lend_apply.version_number
     *
     * @mbggenerated
     */
    public Integer getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.version_number
     *
     * @param versionNumber the value for t_lend_apply.version_number
     *
     * @mbggenerated
     */
    public void setVersionNumber(Integer versionNumber) {
        this.versionNumber = versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.status_desc
     *
     * @return the value of t_lend_apply.status_desc
     *
     * @mbggenerated
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.status_desc
     *
     * @param statusDesc the value for t_lend_apply.status_desc
     *
     * @mbggenerated
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc == null ? null : statusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.account_type
     *
     * @return the value of t_lend_apply.account_type
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.account_type
     *
     * @param accountType the value for t_lend_apply.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.ext_no
     *
     * @return the value of t_lend_apply.ext_no
     *
     * @mbggenerated
     */
    public String getExtNo() {
        return extNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.ext_no
     *
     * @param extNo the value for t_lend_apply.ext_no
     *
     * @mbggenerated
     */
    public void setExtNo(String extNo) {
        this.extNo = extNo == null ? null : extNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.created_at
     *
     * @return the value of t_lend_apply.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.created_at
     *
     * @param createdAt the value for t_lend_apply.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.lend_fee_rate
     *
     * @return the value of t_lend_apply.lend_fee_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLendFeeRate() {
        return lendFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.lend_fee_rate
     *
     * @param lendFeeRate the value for t_lend_apply.lend_fee_rate
     *
     * @mbggenerated
     */
    public void setLendFeeRate(BigDecimal lendFeeRate) {
        this.lendFeeRate = lendFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.customer_irr
     *
     * @return the value of t_lend_apply.customer_irr
     *
     * @mbggenerated
     */
    public BigDecimal getCustomerIrr() {
        return customerIrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.customer_irr
     *
     * @param customerIrr the value for t_lend_apply.customer_irr
     *
     * @mbggenerated
     */
    public void setCustomerIrr(BigDecimal customerIrr) {
        this.customerIrr = customerIrr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.coupon_id
     *
     * @return the value of t_lend_apply.coupon_id
     *
     * @mbggenerated
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.coupon_id
     *
     * @param couponId the value for t_lend_apply.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId == null ? null : couponId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.coupon_type
     *
     * @return the value of t_lend_apply.coupon_type
     *
     * @mbggenerated
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.coupon_type
     *
     * @param couponType the value for t_lend_apply.coupon_type
     *
     * @mbggenerated
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType == null ? null : couponType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.biz_type_tag
     *
     * @return the value of t_lend_apply.biz_type_tag
     *
     * @mbggenerated
     */
    public String getBizTypeTag() {
        return bizTypeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.biz_type_tag
     *
     * @param bizTypeTag the value for t_lend_apply.biz_type_tag
     *
     * @mbggenerated
     */
    public void setBizTypeTag(String bizTypeTag) {
        this.bizTypeTag = bizTypeTag == null ? null : bizTypeTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend_apply.hold_time
     *
     * @return the value of t_lend_apply.hold_time
     *
     * @mbggenerated
     */
    public Date getHoldTime() {
        return holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend_apply.hold_time
     *
     * @param holdTime the value for t_lend_apply.hold_time
     *
     * @mbggenerated
     */
    public void setHoldTime(Date holdTime) {
        this.holdTime = holdTime;
    }
}