package com.caoc.test.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TLendApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public TLendApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoIsNull() {
            addCriterion("`lend_apply_no` is null");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoIsNotNull() {
            addCriterion("`lend_apply_no` is not null");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoEqualTo(String value) {
            addCriterion("`lend_apply_no` =", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoNotEqualTo(String value) {
            addCriterion("`lend_apply_no` <>", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoGreaterThan(String value) {
            addCriterion("`lend_apply_no` >", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("`lend_apply_no` >=", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoLessThan(String value) {
            addCriterion("`lend_apply_no` <", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoLessThanOrEqualTo(String value) {
            addCriterion("`lend_apply_no` <=", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoLike(String value) {
            addCriterion("`lend_apply_no` like", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoNotLike(String value) {
            addCriterion("`lend_apply_no` not like", value, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoIn(List<String> values) {
            addCriterion("`lend_apply_no` in", values, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoNotIn(List<String> values) {
            addCriterion("`lend_apply_no` not in", values, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoBetween(String value1, String value2) {
            addCriterion("`lend_apply_no` between", value1, value2, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andLendApplyNoNotBetween(String value1, String value2) {
            addCriterion("`lend_apply_no` not between", value1, value2, "lendApplyNo");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("`order_no` is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("`order_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("`order_no` =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("`order_no` <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("`order_no` >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("`order_no` >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("`order_no` <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("`order_no` <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("`order_no` like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("`order_no` not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("`order_no` in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("`order_no` not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("`order_no` between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("`order_no` not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialIsNull() {
            addCriterion("`parent_biz_serial` is null");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialIsNotNull() {
            addCriterion("`parent_biz_serial` is not null");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialEqualTo(String value) {
            addCriterion("`parent_biz_serial` =", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialNotEqualTo(String value) {
            addCriterion("`parent_biz_serial` <>", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialGreaterThan(String value) {
            addCriterion("`parent_biz_serial` >", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialGreaterThanOrEqualTo(String value) {
            addCriterion("`parent_biz_serial` >=", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialLessThan(String value) {
            addCriterion("`parent_biz_serial` <", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialLessThanOrEqualTo(String value) {
            addCriterion("`parent_biz_serial` <=", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialLike(String value) {
            addCriterion("`parent_biz_serial` like", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialNotLike(String value) {
            addCriterion("`parent_biz_serial` not like", value, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialIn(List<String> values) {
            addCriterion("`parent_biz_serial` in", values, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialNotIn(List<String> values) {
            addCriterion("`parent_biz_serial` not in", values, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialBetween(String value1, String value2) {
            addCriterion("`parent_biz_serial` between", value1, value2, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andParentBizSerialNotBetween(String value1, String value2) {
            addCriterion("`parent_biz_serial` not between", value1, value2, "parentBizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialIsNull() {
            addCriterion("`biz_serial` is null");
            return (Criteria) this;
        }

        public Criteria andBizSerialIsNotNull() {
            addCriterion("`biz_serial` is not null");
            return (Criteria) this;
        }

        public Criteria andBizSerialEqualTo(String value) {
            addCriterion("`biz_serial` =", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotEqualTo(String value) {
            addCriterion("`biz_serial` <>", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialGreaterThan(String value) {
            addCriterion("`biz_serial` >", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialGreaterThanOrEqualTo(String value) {
            addCriterion("`biz_serial` >=", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLessThan(String value) {
            addCriterion("`biz_serial` <", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLessThanOrEqualTo(String value) {
            addCriterion("`biz_serial` <=", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialLike(String value) {
            addCriterion("`biz_serial` like", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotLike(String value) {
            addCriterion("`biz_serial` not like", value, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialIn(List<String> values) {
            addCriterion("`biz_serial` in", values, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotIn(List<String> values) {
            addCriterion("`biz_serial` not in", values, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialBetween(String value1, String value2) {
            addCriterion("`biz_serial` between", value1, value2, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizSerialNotBetween(String value1, String value2) {
            addCriterion("`biz_serial` not between", value1, value2, "bizSerial");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("`biz_type` is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("`biz_type` is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("`biz_type` =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("`biz_type` <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("`biz_type` >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`biz_type` >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("`biz_type` <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("`biz_type` <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("`biz_type` like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("`biz_type` not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("`biz_type` in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("`biz_type` not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("`biz_type` between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("`biz_type` not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andLendTypeIsNull() {
            addCriterion("`lend_type` is null");
            return (Criteria) this;
        }

        public Criteria andLendTypeIsNotNull() {
            addCriterion("`lend_type` is not null");
            return (Criteria) this;
        }

        public Criteria andLendTypeEqualTo(String value) {
            addCriterion("`lend_type` =", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeNotEqualTo(String value) {
            addCriterion("`lend_type` <>", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeGreaterThan(String value) {
            addCriterion("`lend_type` >", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`lend_type` >=", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeLessThan(String value) {
            addCriterion("`lend_type` <", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeLessThanOrEqualTo(String value) {
            addCriterion("`lend_type` <=", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeLike(String value) {
            addCriterion("`lend_type` like", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeNotLike(String value) {
            addCriterion("`lend_type` not like", value, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeIn(List<String> values) {
            addCriterion("`lend_type` in", values, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeNotIn(List<String> values) {
            addCriterion("`lend_type` not in", values, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeBetween(String value1, String value2) {
            addCriterion("`lend_type` between", value1, value2, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendTypeNotBetween(String value1, String value2) {
            addCriterion("`lend_type` not between", value1, value2, "lendType");
            return (Criteria) this;
        }

        public Criteria andLendCardIdIsNull() {
            addCriterion("`lend_card_id` is null");
            return (Criteria) this;
        }

        public Criteria andLendCardIdIsNotNull() {
            addCriterion("`lend_card_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLendCardIdEqualTo(String value) {
            addCriterion("`lend_card_id` =", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdNotEqualTo(String value) {
            addCriterion("`lend_card_id` <>", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdGreaterThan(String value) {
            addCriterion("`lend_card_id` >", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("`lend_card_id` >=", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdLessThan(String value) {
            addCriterion("`lend_card_id` <", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdLessThanOrEqualTo(String value) {
            addCriterion("`lend_card_id` <=", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdLike(String value) {
            addCriterion("`lend_card_id` like", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdNotLike(String value) {
            addCriterion("`lend_card_id` not like", value, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdIn(List<String> values) {
            addCriterion("`lend_card_id` in", values, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdNotIn(List<String> values) {
            addCriterion("`lend_card_id` not in", values, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdBetween(String value1, String value2) {
            addCriterion("`lend_card_id` between", value1, value2, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andLendCardIdNotBetween(String value1, String value2) {
            addCriterion("`lend_card_id` not between", value1, value2, "lendCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdIsNull() {
            addCriterion("`repay_card_id` is null");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdIsNotNull() {
            addCriterion("`repay_card_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdEqualTo(String value) {
            addCriterion("`repay_card_id` =", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdNotEqualTo(String value) {
            addCriterion("`repay_card_id` <>", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdGreaterThan(String value) {
            addCriterion("`repay_card_id` >", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("`repay_card_id` >=", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdLessThan(String value) {
            addCriterion("`repay_card_id` <", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdLessThanOrEqualTo(String value) {
            addCriterion("`repay_card_id` <=", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdLike(String value) {
            addCriterion("`repay_card_id` like", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdNotLike(String value) {
            addCriterion("`repay_card_id` not like", value, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdIn(List<String> values) {
            addCriterion("`repay_card_id` in", values, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdNotIn(List<String> values) {
            addCriterion("`repay_card_id` not in", values, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdBetween(String value1, String value2) {
            addCriterion("`repay_card_id` between", value1, value2, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andRepayCardIdNotBetween(String value1, String value2) {
            addCriterion("`repay_card_id` not between", value1, value2, "repayCardId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdIsNull() {
            addCriterion("`asset_product_id` is null");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdIsNotNull() {
            addCriterion("`asset_product_id` is not null");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdEqualTo(String value) {
            addCriterion("`asset_product_id` =", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdNotEqualTo(String value) {
            addCriterion("`asset_product_id` <>", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdGreaterThan(String value) {
            addCriterion("`asset_product_id` >", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("`asset_product_id` >=", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdLessThan(String value) {
            addCriterion("`asset_product_id` <", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdLessThanOrEqualTo(String value) {
            addCriterion("`asset_product_id` <=", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdLike(String value) {
            addCriterion("`asset_product_id` like", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdNotLike(String value) {
            addCriterion("`asset_product_id` not like", value, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdIn(List<String> values) {
            addCriterion("`asset_product_id` in", values, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdNotIn(List<String> values) {
            addCriterion("`asset_product_id` not in", values, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdBetween(String value1, String value2) {
            addCriterion("`asset_product_id` between", value1, value2, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetProductIdNotBetween(String value1, String value2) {
            addCriterion("`asset_product_id` not between", value1, value2, "assetProductId");
            return (Criteria) this;
        }

        public Criteria andAssetBankIsNull() {
            addCriterion("`asset_bank` is null");
            return (Criteria) this;
        }

        public Criteria andAssetBankIsNotNull() {
            addCriterion("`asset_bank` is not null");
            return (Criteria) this;
        }

        public Criteria andAssetBankEqualTo(String value) {
            addCriterion("`asset_bank` =", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankNotEqualTo(String value) {
            addCriterion("`asset_bank` <>", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankGreaterThan(String value) {
            addCriterion("`asset_bank` >", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankGreaterThanOrEqualTo(String value) {
            addCriterion("`asset_bank` >=", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankLessThan(String value) {
            addCriterion("`asset_bank` <", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankLessThanOrEqualTo(String value) {
            addCriterion("`asset_bank` <=", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankLike(String value) {
            addCriterion("`asset_bank` like", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankNotLike(String value) {
            addCriterion("`asset_bank` not like", value, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankIn(List<String> values) {
            addCriterion("`asset_bank` in", values, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankNotIn(List<String> values) {
            addCriterion("`asset_bank` not in", values, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankBetween(String value1, String value2) {
            addCriterion("`asset_bank` between", value1, value2, "assetBank");
            return (Criteria) this;
        }

        public Criteria andAssetBankNotBetween(String value1, String value2) {
            addCriterion("`asset_bank` not between", value1, value2, "assetBank");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("`apply_time` is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("`apply_time` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("`apply_time` =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("`apply_time` <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("`apply_time` >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`apply_time` >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("`apply_time` <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("`apply_time` <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("`apply_time` in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("`apply_time` not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("`apply_time` between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("`apply_time` not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNull() {
            addCriterion("`apply_status` is null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIsNotNull() {
            addCriterion("`apply_status` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyStatusEqualTo(String value) {
            addCriterion("`apply_status` =", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotEqualTo(String value) {
            addCriterion("`apply_status` <>", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThan(String value) {
            addCriterion("`apply_status` >", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`apply_status` >=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThan(String value) {
            addCriterion("`apply_status` <", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLessThanOrEqualTo(String value) {
            addCriterion("`apply_status` <=", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusLike(String value) {
            addCriterion("`apply_status` like", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotLike(String value) {
            addCriterion("`apply_status` not like", value, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusIn(List<String> values) {
            addCriterion("`apply_status` in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotIn(List<String> values) {
            addCriterion("`apply_status` not in", values, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusBetween(String value1, String value2) {
            addCriterion("`apply_status` between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andApplyStatusNotBetween(String value1, String value2) {
            addCriterion("`apply_status` not between", value1, value2, "applyStatus");
            return (Criteria) this;
        }

        public Criteria andLendAmountIsNull() {
            addCriterion("`lend_amount` is null");
            return (Criteria) this;
        }

        public Criteria andLendAmountIsNotNull() {
            addCriterion("`lend_amount` is not null");
            return (Criteria) this;
        }

        public Criteria andLendAmountEqualTo(Integer value) {
            addCriterion("`lend_amount` =", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountNotEqualTo(Integer value) {
            addCriterion("`lend_amount` <>", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountGreaterThan(Integer value) {
            addCriterion("`lend_amount` >", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`lend_amount` >=", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountLessThan(Integer value) {
            addCriterion("`lend_amount` <", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountLessThanOrEqualTo(Integer value) {
            addCriterion("`lend_amount` <=", value, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountIn(List<Integer> values) {
            addCriterion("`lend_amount` in", values, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountNotIn(List<Integer> values) {
            addCriterion("`lend_amount` not in", values, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountBetween(Integer value1, Integer value2) {
            addCriterion("`lend_amount` between", value1, value2, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andLendAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("`lend_amount` not between", value1, value2, "lendAmount");
            return (Criteria) this;
        }

        public Criteria andStageIsNull() {
            addCriterion("`stage` is null");
            return (Criteria) this;
        }

        public Criteria andStageIsNotNull() {
            addCriterion("`stage` is not null");
            return (Criteria) this;
        }

        public Criteria andStageEqualTo(Byte value) {
            addCriterion("`stage` =", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotEqualTo(Byte value) {
            addCriterion("`stage` <>", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThan(Byte value) {
            addCriterion("`stage` >", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThanOrEqualTo(Byte value) {
            addCriterion("`stage` >=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThan(Byte value) {
            addCriterion("`stage` <", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThanOrEqualTo(Byte value) {
            addCriterion("`stage` <=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageIn(List<Byte> values) {
            addCriterion("`stage` in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotIn(List<Byte> values) {
            addCriterion("`stage` not in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageBetween(Byte value1, Byte value2) {
            addCriterion("`stage` between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotBetween(Byte value1, Byte value2) {
            addCriterion("`stage` not between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("`source` is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("`source` is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("`source` =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("`source` <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("`source` >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("`source` >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("`source` <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("`source` <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("`source` like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("`source` not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("`source` in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("`source` not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("`source` between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("`source` not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andLendPurposeIsNull() {
            addCriterion("`lend_purpose` is null");
            return (Criteria) this;
        }

        public Criteria andLendPurposeIsNotNull() {
            addCriterion("`lend_purpose` is not null");
            return (Criteria) this;
        }

        public Criteria andLendPurposeEqualTo(String value) {
            addCriterion("`lend_purpose` =", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeNotEqualTo(String value) {
            addCriterion("`lend_purpose` <>", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeGreaterThan(String value) {
            addCriterion("`lend_purpose` >", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("`lend_purpose` >=", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeLessThan(String value) {
            addCriterion("`lend_purpose` <", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeLessThanOrEqualTo(String value) {
            addCriterion("`lend_purpose` <=", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeLike(String value) {
            addCriterion("`lend_purpose` like", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeNotLike(String value) {
            addCriterion("`lend_purpose` not like", value, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeIn(List<String> values) {
            addCriterion("`lend_purpose` in", values, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeNotIn(List<String> values) {
            addCriterion("`lend_purpose` not in", values, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeBetween(String value1, String value2) {
            addCriterion("`lend_purpose` between", value1, value2, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andLendPurposeNotBetween(String value1, String value2) {
            addCriterion("`lend_purpose` not between", value1, value2, "lendPurpose");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIsNull() {
            addCriterion("`interest_type` is null");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIsNotNull() {
            addCriterion("`interest_type` is not null");
            return (Criteria) this;
        }

        public Criteria andInterestTypeEqualTo(String value) {
            addCriterion("`interest_type` =", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotEqualTo(String value) {
            addCriterion("`interest_type` <>", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeGreaterThan(String value) {
            addCriterion("`interest_type` >", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`interest_type` >=", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLessThan(String value) {
            addCriterion("`interest_type` <", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLessThanOrEqualTo(String value) {
            addCriterion("`interest_type` <=", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeLike(String value) {
            addCriterion("`interest_type` like", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotLike(String value) {
            addCriterion("`interest_type` not like", value, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeIn(List<String> values) {
            addCriterion("`interest_type` in", values, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotIn(List<String> values) {
            addCriterion("`interest_type` not in", values, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeBetween(String value1, String value2) {
            addCriterion("`interest_type` between", value1, value2, "interestType");
            return (Criteria) this;
        }

        public Criteria andInterestTypeNotBetween(String value1, String value2) {
            addCriterion("`interest_type` not between", value1, value2, "interestType");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNull() {
            addCriterion("`fee_rate` is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNotNull() {
            addCriterion("`fee_rate` is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateEqualTo(BigDecimal value) {
            addCriterion("`fee_rate` =", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("`fee_rate` <>", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThan(BigDecimal value) {
            addCriterion("`fee_rate` >", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`fee_rate` >=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThan(BigDecimal value) {
            addCriterion("`fee_rate` <", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`fee_rate` <=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateIn(List<BigDecimal> values) {
            addCriterion("`fee_rate` in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("`fee_rate` not in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`fee_rate` between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`fee_rate` not between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("`updated_at` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("`updated_at` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("`updated_at` =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("`updated_at` <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("`updated_at` >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_at` >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("`updated_at` <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`updated_at` <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("`updated_at` in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("`updated_at` not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("`updated_at` between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`updated_at` not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("`create_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("`create_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("`create_by` =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("`create_by` <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("`create_by` >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("`create_by` >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("`create_by` <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("`create_by` <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("`create_by` like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("`create_by` not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("`create_by` in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("`create_by` not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("`create_by` between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("`create_by` not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("`update_by` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("`update_by` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("`update_by` =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("`update_by` <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("`update_by` >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("`update_by` >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("`update_by` <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("`update_by` <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("`update_by` like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("`update_by` not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("`update_by` in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("`update_by` not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("`update_by` between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("`update_by` not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNull() {
            addCriterion("`version_number` is null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIsNotNull() {
            addCriterion("`version_number` is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNumberEqualTo(Integer value) {
            addCriterion("`version_number` =", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotEqualTo(Integer value) {
            addCriterion("`version_number` <>", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThan(Integer value) {
            addCriterion("`version_number` >", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("`version_number` >=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThan(Integer value) {
            addCriterion("`version_number` <", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberLessThanOrEqualTo(Integer value) {
            addCriterion("`version_number` <=", value, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberIn(List<Integer> values) {
            addCriterion("`version_number` in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotIn(List<Integer> values) {
            addCriterion("`version_number` not in", values, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberBetween(Integer value1, Integer value2) {
            addCriterion("`version_number` between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andVersionNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("`version_number` not between", value1, value2, "versionNumber");
            return (Criteria) this;
        }

        public Criteria andStatusDescIsNull() {
            addCriterion("`status_desc` is null");
            return (Criteria) this;
        }

        public Criteria andStatusDescIsNotNull() {
            addCriterion("`status_desc` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusDescEqualTo(String value) {
            addCriterion("`status_desc` =", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescNotEqualTo(String value) {
            addCriterion("`status_desc` <>", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescGreaterThan(String value) {
            addCriterion("`status_desc` >", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescGreaterThanOrEqualTo(String value) {
            addCriterion("`status_desc` >=", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescLessThan(String value) {
            addCriterion("`status_desc` <", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescLessThanOrEqualTo(String value) {
            addCriterion("`status_desc` <=", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescLike(String value) {
            addCriterion("`status_desc` like", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescNotLike(String value) {
            addCriterion("`status_desc` not like", value, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescIn(List<String> values) {
            addCriterion("`status_desc` in", values, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescNotIn(List<String> values) {
            addCriterion("`status_desc` not in", values, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescBetween(String value1, String value2) {
            addCriterion("`status_desc` between", value1, value2, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andStatusDescNotBetween(String value1, String value2) {
            addCriterion("`status_desc` not between", value1, value2, "statusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNull() {
            addCriterion("`account_type` is null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNotNull() {
            addCriterion("`account_type` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeEqualTo(String value) {
            addCriterion("`account_type` =", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotEqualTo(String value) {
            addCriterion("`account_type` <>", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThan(String value) {
            addCriterion("`account_type` >", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`account_type` >=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThan(String value) {
            addCriterion("`account_type` <", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThanOrEqualTo(String value) {
            addCriterion("`account_type` <=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLike(String value) {
            addCriterion("`account_type` like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotLike(String value) {
            addCriterion("`account_type` not like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIn(List<String> values) {
            addCriterion("`account_type` in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotIn(List<String> values) {
            addCriterion("`account_type` not in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeBetween(String value1, String value2) {
            addCriterion("`account_type` between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotBetween(String value1, String value2) {
            addCriterion("`account_type` not between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andExtNoIsNull() {
            addCriterion("`ext_no` is null");
            return (Criteria) this;
        }

        public Criteria andExtNoIsNotNull() {
            addCriterion("`ext_no` is not null");
            return (Criteria) this;
        }

        public Criteria andExtNoEqualTo(String value) {
            addCriterion("`ext_no` =", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoNotEqualTo(String value) {
            addCriterion("`ext_no` <>", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoGreaterThan(String value) {
            addCriterion("`ext_no` >", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoGreaterThanOrEqualTo(String value) {
            addCriterion("`ext_no` >=", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoLessThan(String value) {
            addCriterion("`ext_no` <", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoLessThanOrEqualTo(String value) {
            addCriterion("`ext_no` <=", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoLike(String value) {
            addCriterion("`ext_no` like", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoNotLike(String value) {
            addCriterion("`ext_no` not like", value, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoIn(List<String> values) {
            addCriterion("`ext_no` in", values, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoNotIn(List<String> values) {
            addCriterion("`ext_no` not in", values, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoBetween(String value1, String value2) {
            addCriterion("`ext_no` between", value1, value2, "extNo");
            return (Criteria) this;
        }

        public Criteria andExtNoNotBetween(String value1, String value2) {
            addCriterion("`ext_no` not between", value1, value2, "extNo");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("`created_at` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("`created_at` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("`created_at` =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("`created_at` <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("`created_at` >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_at` >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("`created_at` <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("`created_at` <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("`created_at` in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("`created_at` not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("`created_at` between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("`created_at` not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateIsNull() {
            addCriterion("`lend_fee_rate` is null");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateIsNotNull() {
            addCriterion("`lend_fee_rate` is not null");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateEqualTo(BigDecimal value) {
            addCriterion("`lend_fee_rate` =", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("`lend_fee_rate` <>", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateGreaterThan(BigDecimal value) {
            addCriterion("`lend_fee_rate` >", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`lend_fee_rate` >=", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateLessThan(BigDecimal value) {
            addCriterion("`lend_fee_rate` <", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`lend_fee_rate` <=", value, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateIn(List<BigDecimal> values) {
            addCriterion("`lend_fee_rate` in", values, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("`lend_fee_rate` not in", values, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`lend_fee_rate` between", value1, value2, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andLendFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`lend_fee_rate` not between", value1, value2, "lendFeeRate");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrIsNull() {
            addCriterion("`customer_irr` is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrIsNotNull() {
            addCriterion("`customer_irr` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrEqualTo(BigDecimal value) {
            addCriterion("`customer_irr` =", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrNotEqualTo(BigDecimal value) {
            addCriterion("`customer_irr` <>", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrGreaterThan(BigDecimal value) {
            addCriterion("`customer_irr` >", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`customer_irr` >=", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrLessThan(BigDecimal value) {
            addCriterion("`customer_irr` <", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`customer_irr` <=", value, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrIn(List<BigDecimal> values) {
            addCriterion("`customer_irr` in", values, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrNotIn(List<BigDecimal> values) {
            addCriterion("`customer_irr` not in", values, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`customer_irr` between", value1, value2, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCustomerIrrNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`customer_irr` not between", value1, value2, "customerIrr");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("`coupon_id` is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("`coupon_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(String value) {
            addCriterion("`coupon_id` =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(String value) {
            addCriterion("`coupon_id` <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(String value) {
            addCriterion("`coupon_id` >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(String value) {
            addCriterion("`coupon_id` >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(String value) {
            addCriterion("`coupon_id` <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(String value) {
            addCriterion("`coupon_id` <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLike(String value) {
            addCriterion("`coupon_id` like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotLike(String value) {
            addCriterion("`coupon_id` not like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<String> values) {
            addCriterion("`coupon_id` in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<String> values) {
            addCriterion("`coupon_id` not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(String value1, String value2) {
            addCriterion("`coupon_id` between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(String value1, String value2) {
            addCriterion("`coupon_id` not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponTypeIsNull() {
            addCriterion("`coupon_type` is null");
            return (Criteria) this;
        }

        public Criteria andCouponTypeIsNotNull() {
            addCriterion("`coupon_type` is not null");
            return (Criteria) this;
        }

        public Criteria andCouponTypeEqualTo(String value) {
            addCriterion("`coupon_type` =", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeNotEqualTo(String value) {
            addCriterion("`coupon_type` <>", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeGreaterThan(String value) {
            addCriterion("`coupon_type` >", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`coupon_type` >=", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeLessThan(String value) {
            addCriterion("`coupon_type` <", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeLessThanOrEqualTo(String value) {
            addCriterion("`coupon_type` <=", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeLike(String value) {
            addCriterion("`coupon_type` like", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeNotLike(String value) {
            addCriterion("`coupon_type` not like", value, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeIn(List<String> values) {
            addCriterion("`coupon_type` in", values, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeNotIn(List<String> values) {
            addCriterion("`coupon_type` not in", values, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeBetween(String value1, String value2) {
            addCriterion("`coupon_type` between", value1, value2, "couponType");
            return (Criteria) this;
        }

        public Criteria andCouponTypeNotBetween(String value1, String value2) {
            addCriterion("`coupon_type` not between", value1, value2, "couponType");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagIsNull() {
            addCriterion("`biz_type_tag` is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagIsNotNull() {
            addCriterion("`biz_type_tag` is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagEqualTo(String value) {
            addCriterion("`biz_type_tag` =", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagNotEqualTo(String value) {
            addCriterion("`biz_type_tag` <>", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagGreaterThan(String value) {
            addCriterion("`biz_type_tag` >", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagGreaterThanOrEqualTo(String value) {
            addCriterion("`biz_type_tag` >=", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagLessThan(String value) {
            addCriterion("`biz_type_tag` <", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagLessThanOrEqualTo(String value) {
            addCriterion("`biz_type_tag` <=", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagLike(String value) {
            addCriterion("`biz_type_tag` like", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagNotLike(String value) {
            addCriterion("`biz_type_tag` not like", value, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagIn(List<String> values) {
            addCriterion("`biz_type_tag` in", values, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagNotIn(List<String> values) {
            addCriterion("`biz_type_tag` not in", values, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagBetween(String value1, String value2) {
            addCriterion("`biz_type_tag` between", value1, value2, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andBizTypeTagNotBetween(String value1, String value2) {
            addCriterion("`biz_type_tag` not between", value1, value2, "bizTypeTag");
            return (Criteria) this;
        }

        public Criteria andHoldTimeIsNull() {
            addCriterion("`hold_time` is null");
            return (Criteria) this;
        }

        public Criteria andHoldTimeIsNotNull() {
            addCriterion("`hold_time` is not null");
            return (Criteria) this;
        }

        public Criteria andHoldTimeEqualTo(Date value) {
            addCriterion("`hold_time` =", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeNotEqualTo(Date value) {
            addCriterion("`hold_time` <>", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeGreaterThan(Date value) {
            addCriterion("`hold_time` >", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`hold_time` >=", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeLessThan(Date value) {
            addCriterion("`hold_time` <", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeLessThanOrEqualTo(Date value) {
            addCriterion("`hold_time` <=", value, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeIn(List<Date> values) {
            addCriterion("`hold_time` in", values, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeNotIn(List<Date> values) {
            addCriterion("`hold_time` not in", values, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeBetween(Date value1, Date value2) {
            addCriterion("`hold_time` between", value1, value2, "holdTime");
            return (Criteria) this;
        }

        public Criteria andHoldTimeNotBetween(Date value1, Date value2) {
            addCriterion("`hold_time` not between", value1, value2, "holdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lend_apply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_lend_apply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}